export const curriculum = [
  {
    company: "Dream Labs Cozumel",
    title: "Fullstack Blockchain App Developer",
    companyType: "Self-employed",
    date: "Aug 2021 – Present",
    duration: "4 months",
    location: "Cozumel, Quintana Roo, Mexico",
    desc: "Venturing into the realms of the blockchain... And oh boy, has it been a journey so far. I deeply appreciate the power, creativity and freedom that blockchains unleash, not only for developers. I started building decentralized Apps (dApps), smart contracts and playing around with all the new tools in general. The potential is huge, much more to come soon!",
    latestProject: "https://deez-nutz-dapp.vercel.app/",
    skills: ["Solidity", "Web3", "ethers.js", "hardhat", "truffle", "IPFS", "NFTs", "Tokenomics"],
  },
  {
    company: "shift-happens",
    title: "Full Stack Engineer",
    companyType: "Self-employed",
    date: "Jan 2021 – Present",
    duration: "11 months",
    location: "Cozumel, Quintana Roo, Mexico",
    desc: "After having travelled Asia for 3 years and endured the first Covid-19 related lockdowns in Nepal, a project brought me to Mexico. Jumping right back into JavaScript I was pleased to see so much change, so many new tools! NextJS, Svelte, Tailwind, Vercel, JamStack, GraphQL, Parcel, JAM... the ecosystem has never been better. I have since had the opportunity to do many interesting projects. <a href='/contact'>Contact me</a>, if you think synergies could arise.",
    latestProject: "https://www.czmstem.com/",
    skills: ["Web/Fullstack/Mobile", "NextJS", "Svelte", "Tailwind", "Parcel", "Vercel", "JamStack", "Serverless"],
  },
  {
    company: "shift_happens_yoga",
    title: "Yoga Teacher",
    companyType: "Self-employed",
    date: "Jan 2018 – Present",
    duration: "3 yrs 11 months",
    location: "Thailand, Indonesia, India, Nepal, ...",
    desc: "In 2018, struggling deeply with depression and addiction, I quit my job as developer in Barcelona, started travelling and discovered Yoga. I enrolled in a 200h Yoga teacher training course in Thailand. An eye-opening experience that changed my life forever. I have been practicing and teaching Yoga since. The name shift_happens is based on the immense sudden shift my life took and from the prospect that Yoga can help healing. I am also Yoga Alliance RYT-500 and ERYT-200 certified.",
    latestProject: "https://www.christof.digital/yoga",
    skills: ["Ashtanga primary & intermediate series", "Yoga for Martial Artists", "Anatomy for Yoga and TTCs", "Pranayama", "Pre-YTT trainings", "Yoga and mental health"]
  },
  {
    company: "XING AG",
    title: "Frontend Engineer",
    companyType: "Full-Time Employee (1000+ employees)",
    companyUrl: "https://www.xing.com/",
    date: "Aug 2014 – Jan 2018",
    duration: "3 years 6 months",
    location: "Hamburg, Germany",
    desc: "Xing is the LinkedIn of the German speaking market. It is now a unicorn, with more than a 1000 employees over 5 countries, but still felt like a startup. I joined the headquarters in Hamburg as Frontend Engineer for the Premium/ProJobs team. It was a great, enthusiastic atmosphere and until today my longest commitment towards a company. In late 2016 I switched to our newly opened Barcelona office to support and build up the team. Fun fact: Xing was supposed to be pronounced Crossing/X-ing, but instead the German public just calls it Xing with a hard X. Entertaining marketing-fail 101.",
    latestProject: "https://www.xing.de/projobs",
    skills: ["React", "Git", "TravisCI", "Scrum", "Kanban"]
  },
  {
    company: "Gruner + Jahr GmbH & Co KG",
    title: "System Engineer",
    companyType: "Full-Time Employee (1,500+ employees)",
    companyUrl: "https://www.guj.de/",
    date: "Oct 2012 – Jul 2014",
    duration: "1 year 10 months",
    location: "Hamburg, Germany",
    desc: "G&J is (was) the biggest publishing company in Germany with titles like National Geographic, Financial Times Deutschland or Stern. G&J hosted all its infrastructure in house (crazy, I know) and as part of G+J Digital Products we were responsible for keeping it all running... 24/7. Another task was to provide all dev and staging environments for the different teams, deployments, build chains, Url rewrites, virtualization... G&J is very traditional and very slow to adjust to challenges of the new digital age, still it was a very valuable learning expierence for me.",
    latestProject: "Production Setup for Brigitte.de, Gala.de, Geo.de. ",
    skills: ["Shell", "Perl", "PHP", "VMWare", "Apache", "NGinx"]
  },
  {
    company: "Futura Epsis 1",
    title: "Senior Lead Developer",
    companyType: "Self-employed",
    companyUrl: "https://www.futura-epsis1.com/",
    date: "Apr 2012 – Sep 2012",
    duration: "6 months",
    location: "Hamburg, Germany",
    desc: "With the digital artist I mentioned earlier, we created digital experiences for brands, agencies, art curators, labels and musicians. Whereas he was creating the art, I was responsible for all backend related tasks. One project was to develop a massive multitouch table, working with a beamer and resistive touchscreen - but in March the same year Apple launched the iPad and pretty much made all these ideas obolete. Our cooperation was nonetheless a fruitful endeavour.",
    latestProject: "Multitouch device just before the iPad launched...",
    skills: ["ActionScript", "PHP", "Apache", "JQuery"]
  },
  {
    company: "Trakken Technologies GmbH",
    title: "Web-Developer",
    companyUrl: "https://www.trakkenwebservices.com/",
    companyType: "Full-Time Employee (~10 employees)",
    date: "Feb 2010 – May 2012",
    duration: "2 years 4 months",
    location: "Hamburg, Germany",
    desc: "In early 2010 I joined the just founded startup Trakken Technologies, becoming part of a 3 person dev team. It was wild, fiddling with JavaScript, setting up and managing our own servers, failing deployments on Friday, the usual early quirks. Main product was <a href='https://www.trakkenwebservices.com/products/trakkboard/' target='_blank' rel='noopener noreferrer nofollow'>TrakkBoard</a>, a SaaS solution for web controlling, a sort of digital data platform, the analytics for marketers. It's still out there.",
    latestProject: "https://www.trakkenwebservices.com/products/trakkboard/",
    skills: ["Ruby on Rails", "PHP", "Hadoop", "JQuery", "MongoDB", "HBase", "redis"]
  },
  {
    company: "thirtyOne Media",
    title: "PHP & ActionScript Programmer",
    companyType: "Freelance",
    companyUrl: "https://thirtyonedigital.com/",
    date: "Oct 2008 – Feb 2010",
    duration: "1 year 5 months",
    location: "Hamburg, Germany",
    desc: "This was my first real attempt to do more independent projects as freelancer. I partnered with Andreas Rothaug, a digital artist from Hamburg and together we built RIAs (Rich Internet Applications) with a Flash frontend and a PHP backend. Our clients were mainly digital marketing agencies and affiliates.",
    latestProject: "Gateway between Flash (ActionScript3) and PHP with AMF",
    skills: ["ActionScript3", "PHP", "LAMP", "Zend"]
  },
  {
    company: "eSearchVision",
    title: "SEM Account Manager",
    companyType: "Full-Time Employee (~40 employees)",
    companyUrl: "https://www.esvdigital.com/",
    date: "2007 – 2008",
    duration: "1 year",
    location: "Paris, France",
    desc: "Founded in 2004 and expanding to the US in 2006, I worked at eSV as SEM Manager on ad campaigns for clients like Apple, Scout24 or Filemaker, mainly for the German market. This was quite an intense, KPI driven environment, but at the same time very insightful to work in a truly international team. For me this was the first time that English was the main company language.",
    latestProject: "Apple Product Red campaign",
    skills: ["AdSense", "Analytics", "Target CPC optimization"]
  },
  {
    company: "Pangora SAS",
    title: "SEM Manager",
    companyType: "Full-Time Employee (~40 employees)",
    date: "May 2007 – Oct 2007",
    duration: "6 months",
    location: "Paris, France",
    desc: "This was my first 'real' job after graduating! Additionally, in a new city in a whole new country: Paris, France. Well, not really, I used to live there in my childhood. But this time, I came for something different. I worked in Search Engine Marketing (SEM), mostly for price comparison sites. (buycentral.de, shopping.lycos.de...). Very analytical position trying to optimize CPC/CPO for longtail searchterms.",
    latestProject: "",
    skills: ["AdSense", "CPC optimization"]
  },
  {
    company: "mentasys GmbH",
    title: "Graduand",
    companyType: "Full-Time Employee (~40 employees)",
    date: "2006 – 2007",
    duration: "1 year",
    location: "Karlsruhe, Germany",
    desc: "I wrote my Master Thesis about building webshops. mentasys needed one and supported my work to finalize the web portal youSmile.de.",
    latestProject: "Technical and conceptual Redesign and Relaunch of the Web portal youSmile.de",
    skills: ["HTML", "CSS2", "PHP", "JQuery"]
  },
]
